# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the ext4l filesystem (Linux port)
#

obj-y := interface.o stub.o

obj-y	+= balloc.o bitmap.o block_validity.o ext4_jbd2.o extents.o \
		extents_status.o hash.o ialloc.o indirect.o
