# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the ext4l filesystem (Linux port)
#

obj-y := interface.o stub.o

obj-y	+= balloc.o bitmap.o block_validity.o dir.o ext4_jbd2.o extents.o \
		extents_status.o file.o fsync.o hash.o ialloc.o \
		indirect.o inline.o inode.o namei.o super.o symlink.o xattr.o \
		xattr_hurd.o xattr_trusted.o \
		xattr_user.o orphan.o
